spring.application.name=spendwisebackend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

logging.level.com.spendwise=INFO
logging.level.org.springframework=INFO

spring.threads.virtual.enabled=true
server.http2.enabled=true

spring.main.allow-bean-definition-overriding=false

security.jwt.secret-key=${JWT_SECRET_KEY}
app.jwt.expiration-in-ms=${JWT_EXPIRATION_IN_MS}
app.jwt.remember-me-expiration-in-ms=${JWT_REMEMBER_ME_EXPIRATION_IN_MS}

spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

spring.datasource.hikari.maximum-pool-size=20

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.repositories.enabled=false

spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when-authorized

server.servlet.session.cookie.same-site=${SAME_SITE}