import pandas as pd
import numpy as np
import os
import re

def parse_financial_sms(df):
    """
    Parses the SMS body using Regex to extract precise financial details
    and accurately segregate financial from non-financial messages.
    """
    # 1. Base rule: identify explicit spam/ads based on common keywords
    ad_keywords = r'(?i)(?:recharge|data pack|data loan|validity|playlist|subscription|claim|ott|netflix|jiohotstar|zee5|apple music|free access|call alert|hello tune|missed call)'
    
    # 2. Amount Extraction
    # Matches patterns like Rs. 500, INR 1000, Rs 50.00
    amount_pattern = r'(?i)(?:Rs\.?|INR)\s*([\d,]+\.?\d*)'
    # Sometimes amount is like 'debited by 500' without Rs.
    alt_amount_pattern = r'(?i)(?:debited by|credited by)\s*([\d,]+\.?\d*)'
    
    # Extract amounts
    amt_match = df['body'].str.extract(amount_pattern)[0]
    alt_amt_match = df['body'].str.extract(alt_amount_pattern)[0]
    df['parsed_amount'] = amt_match.fillna(alt_amt_match)
    
    # Clean up amount string and convert to numeric
    df['parsed_amount'] = pd.to_numeric(df['parsed_amount'].str.replace(',', '', regex=False), errors='coerce')
    
    # 3. Direction Extraction (Credit / Debit)
    debit_keywords = r'(?i)(?:debited|deducted|paid|spent|withdrawn)'
    credit_keywords = r'(?i)(?:credited|received|added|refunded)'
    
    conditions = [
        df['body'].str.contains(debit_keywords, na=False),
        df['body'].str.contains(credit_keywords, na=False)
    ]
    choices = ['DEBIT', 'CREDIT']
    df['parsed_direction'] = np.select(conditions, choices, default=None)
    
    # 4. Reference ID Extraction
    ref_pattern = r'(?i)(?:Refno|Ref No|Txn ID|Transaction ID|UPI Ref|TxnNo)\s*[:\-]?\s*([A-Za-z0-9]+)'
    df['parsed_ref_id'] = df['body'].str.extract(ref_pattern)[0]
    
    # 5. Entity Extraction (Recipient/Sender)
    # Catch more variations like "transfer to", "Transferred to"
    entity_debit_pattern = r'(?i)(?:trf to|transfer to|transferred to)\s+(.*?)\s+(?:Refno|Ref |UPI|Txn|Avl|dt\s|\()'
    # Catch variations like "by a/c linked to"
    entity_credit_pattern = r'(?i)(?:transfer from|by a/c linked to)\s+(.*?)\s+(?:Ref No|Ref |UPI|Txn|\()'
    
    ent_debit = df['body'].str.extract(entity_debit_pattern)[0]
    ent_credit = df['body'].str.extract(entity_credit_pattern)[0]
    
    # If body extraction fails, fallback to the SMS Sender ID (e.g., 'AX-SLCEIT' -> 'SLCEIT')
    # A typical sender is 2 letters, hyphen, then name. We can strip the prefix/suffix.
    sender_clean = df['sender'].str.replace(r'^[A-Z]{2}-|-?[A-Z]$', '', regex=True)
    
    df['parsed_entity'] = ent_debit.fillna(ent_credit).fillna(sender_clean)
    
    # 6. Final Financial Labeling
    # A message is truly financial if it has an amount, a direction, AND is not an ad
    is_ad = df['body'].str.contains(ad_keywords, na=False) | df['sender'].str.contains(r'(?i)(?:AIRTEL|JIO|VI|650025|BURKIN|ZUDIO|PTRENG)', na=False)
    
    has_financial_info = df['parsed_amount'].notna() & df['parsed_direction'].notna() & (df['parsed_amount'] > 0)
    
    df['parsed_is_financial'] = has_financial_info & (~is_ad)
    
    return df

def prepare_data_for_eda(input_file="captured_sms.csv", output_file="clean_sms_eda.csv"):
    """
    Cleans the captured SMS data for EDA:
    1. Removes duplicates based on ID
    2. Sorts by timestamp
    3. Adds a 'date' column for easier analysis
    4. Parses using robust Regex
    """
    if not os.path.exists(input_file):
        print(f"❌ Error: {input_file} not found. Please sync some data first!")
        return

    print(f"📊 Loading {input_file}...")
    df = pd.read_csv(input_file)

    # 1. Remove duplicates
    initial_count = len(df)
    # 'id' is generated by the app, so it might be unique even for the same SMS.
    # We should drop based on the actual message content and time it was received.
    df = df.drop_duplicates(subset=['body', 'timestamp_ms'])
    print(f"🧹 Removed {initial_count - len(df)} duplicate records.")

    # 2. Sort by time (Oldest to Newest)
    df = df.sort_values(by='timestamp_ms', ascending=True)

    # 3. Add a simple Date column (YYYY-MM-DD)
    df['date'] = df['timestamp_human'].apply(lambda x: str(x).split(' ')[0])

    # 4. Parse Financial details using Regex
    print("🔍 Parsing financial details using Regex...")
    df = parse_financial_sms(df)
    
    # 5. Overwrite unreliable columns with parsed columns
    df['is_financial'] = df['parsed_is_financial']
    df['amount'] = df['parsed_amount']
    df['direction'] = df['parsed_direction']
    df['ref_id'] = df['parsed_ref_id']
    df['entity'] = df['parsed_entity']
    
    # Drop intermediate parsed columns to keep it clean
    cols_to_drop = ['parsed_is_financial', 'parsed_amount', 'parsed_direction', 'parsed_ref_id', 'parsed_entity']
    df = df.drop(columns=cols_to_drop)

    # 6. Save clean version
    df.to_csv(output_file, index=False)
    print(f"✅ Success! Clean data saved to: {output_file}")
    print(f"📈 Total unique SMS available for EDA: {len(df)}")
    
    # Quick Summary
    financial_count = df[df['is_financial'] == True].shape[0]
    print(f"💰 True Financial Messages: {financial_count}")
    print(f"📝 Non-Financial (Ads, OTPs, etc): {len(df) - financial_count}")
    
    # 7. Save a dedicated CSV for ONLY financial data
    financial_df = df[df['is_financial'] == True]
    financial_output_file = "true_financial_sms.csv"
    financial_df.to_csv(financial_output_file, index=False)
    print(f"💾 Saved strictly financial data to: {financial_output_file}")

if __name__ == "__main__":
    prepare_data_for_eda()
